export interface BrowserState {
  primaryColor: string;
  accentColor: string;
  layout: 'minimal' | 'standard' | 'full';
  hasPlayer: boolean;
  hasSidebar: boolean;
  hasSearch: boolean;
  hasPlaylists: boolean;
  hasProfiles: boolean;
  hasSocial: boolean;
  hasLyrics: boolean;
  isDarkMode: boolean;
  heroText: string;
  playerFeatures: string[];
  sidebarItems: string[];
}

export interface Version {
  id: string;
  timestamp: Date;
  title: string;
  version: string;
  description: string;
  features: string[];
  browserState: BrowserState;
  changeTitle: string; // Human-readable title for timeline
}

const now = new Date();

// Array is ordered from OLDEST to NEWEST (index 0 = oldest, last index = newest)
// This matches the visual stack where old versions are far away and new ones are close
export const mockVersions: Version[] = [
  {
    id: 'version-1',
    timestamp: new Date(now.getTime() - 11 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v0.5.0 Alpha',
    description: 'Initial alpha prototype introducing the core concept of a modern music streaming platform.',
    changeTitle: 'Initial alpha release',
    features: [
      'Landing Page',
      'Basic Routing',
    ],
    browserState: {
      primaryColor: '#8B5CF6',
      accentColor: '#A78BFA',
      layout: 'minimal',
      hasPlayer: false,
      hasSidebar: false,
      hasSearch: false,
      hasPlaylists: false,
      hasProfiles: false,
      hasSocial: false,
      hasLyrics: false,
      isDarkMode: false,
      heroText: 'Welcome to MusicFlow',
      playerFeatures: [],
      sidebarItems: ['Home'],
    },
  },
  {
    id: 'version-2',
    timestamp: new Date(now.getTime() - 10 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v0.9.0 Beta',
    description: 'Beta release for testing authentication flow and user account creation.',
    changeTitle: 'Added login & signup',
    features: [
      'Basic Login/Signup',
    ],
    browserState: {
      primaryColor: '#8B5CF6',
      accentColor: '#A78BFA',
      layout: 'minimal',
      hasPlayer: false,
      hasSidebar: false,
      hasSearch: false,
      hasPlaylists: false,
      hasProfiles: false,
      hasSocial: false,
      hasLyrics: false,
      isDarkMode: false,
      heroText: 'Sign in to MusicFlow',
      playerFeatures: [],
      sidebarItems: ['Home', 'Login'],
    },
  },
  {
    id: 'version-3',
    timestamp: new Date(now.getTime() - 9 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v1.0.0',
    description: 'First stable release with basic music playback and user authentication.',
    changeTitle: 'Music player launched',
    features: [
      'User Authentication',
      'Basic Music Playback (Play/Pause, Skip)',
    ],
    browserState: {
      primaryColor: '#7C3AED',
      accentColor: '#A78BFA',
      layout: 'standard',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: false,
      hasPlaylists: false,
      hasProfiles: false,
      hasSocial: false,
      hasLyrics: false,
      isDarkMode: false,
      heroText: 'Your Music, Your Way',
      playerFeatures: ['Play/Pause', 'Skip'],
      sidebarItems: ['Home', 'Browse'],
    },
  },
  {
    id: 'version-4',
    timestamp: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v1.2.0',
    description: 'Personalization update with user profiles and enhanced playback controls.',
    changeTitle: 'User profiles introduced',
    features: [
      'User Authentication',
      'User Profiles',
      'Volume Control',
    ],
    browserState: {
      primaryColor: '#7C3AED',
      accentColor: '#A78BFA',
      layout: 'standard',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: false,
      hasPlaylists: false,
      hasProfiles: true,
      hasSocial: false,
      hasLyrics: false,
      isDarkMode: false,
      heroText: 'Your Music, Your Way',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume'],
      sidebarItems: ['Home', 'Browse', 'Profile'],
    },
  },
  {
    id: 'version-5',
    timestamp: new Date(now.getTime() - 7 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v1.4.0',
    description: 'Major update introducing music library management and custom playlist creation.',
    changeTitle: 'Library & playlists added',
    features: [
      'User Authentication',
      'Music Library',
      'Custom Playlists',
      'Repeat Mode',
    ],
    browserState: {
      primaryColor: '#7C3AED',
      accentColor: '#A78BFA',
      layout: 'standard',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: false,
      hasPlaylists: true,
      hasProfiles: true,
      hasSocial: false,
      hasLyrics: false,
      isDarkMode: false,
      heroText: 'Discover & Play',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume', 'Repeat'],
      sidebarItems: ['Home', 'Browse', 'Library', 'Profile'],
    },
  },
  {
    id: 'version-6',
    timestamp: new Date(now.getTime() - 6 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v1.6.0',
    description: 'Discovery update with powerful search capabilities across millions of tracks.',
    changeTitle: 'Search functionality released',
    features: [
      'Music Search',
      'Artist & Album Discovery',
      'Shuffle Mode',
      'Play Queue Management',
    ],
    browserState: {
      primaryColor: '#6D28D9',
      accentColor: '#8B5CF6',
      layout: 'standard',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: true,
      hasPlaylists: true,
      hasProfiles: true,
      hasSocial: false,
      hasLyrics: false,
      isDarkMode: false,
      heroText: 'Search, Discover, Play',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume', 'Repeat', 'Shuffle'],
      sidebarItems: ['Home', 'Search', 'Library', 'Profile'],
    },
  },
  {
    id: 'version-7',
    timestamp: new Date(now.getTime() - 5 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v1.8.0',
    description: 'Social update bringing music sharing and friend activity features to the platform.',
    changeTitle: 'Social sharing enabled',
    features: [
      'Friend Activity Feed',
      'Playlist Sharing',
      'Collaborative Playlists',
      'Queue Management',
    ],
    browserState: {
      primaryColor: '#6D28D9',
      accentColor: '#8B5CF6',
      layout: 'standard',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: true,
      hasPlaylists: true,
      hasProfiles: true,
      hasSocial: true,
      hasLyrics: false,
      isDarkMode: false,
      heroText: 'Share Your Vibe',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume', 'Repeat', 'Shuffle', 'Queue'],
      sidebarItems: ['Home', 'Search', 'Library', 'Friends', 'Profile'],
    },
  },
  {
    id: 'version-8',
    timestamp: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v2.0.0',
    description: 'Major 2.0 release with professional audio controls and enhanced sound customization.',
    changeTitle: 'Enhanced player with EQ',
    features: [
      'Audio Equalizer (EQ)',
      'Enhanced Audio Engine',
      'Advanced Playlist Management',
      'Radio Stations',
    ],
    browserState: {
      primaryColor: '#5B21B6',
      accentColor: '#7C3AED',
      layout: 'full',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: true,
      hasPlaylists: true,
      hasProfiles: true,
      hasSocial: true,
      hasLyrics: false,
      isDarkMode: false,
      heroText: 'Music That Moves You',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume', 'Repeat', 'Shuffle', 'Queue', 'EQ'],
      sidebarItems: ['Home', 'Search', 'Library', 'Playlists', 'Friends', 'Profile'],
    },
  },
  {
    id: 'version-9',
    timestamp: new Date(now.getTime() - 3 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v2.1.0',
    description: 'Immersive listening experience with real-time synchronized lyrics display.',
    changeTitle: 'Lyrics support added',
    features: [
      'Real-time Lyrics Display',
      'Time-synced Lyrics',
      'Podcast Support',
      'Enhanced Audio Quality',
    ],
    browserState: {
      primaryColor: '#5B21B6',
      accentColor: '#7C3AED',
      layout: 'full',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: true,
      hasPlaylists: true,
      hasProfiles: true,
      hasSocial: true,
      hasLyrics: true,
      isDarkMode: false,
      heroText: 'Feel Every Word',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume', 'Repeat', 'Shuffle', 'Queue', 'EQ', 'Lyrics'],
      sidebarItems: ['Home', 'Search', 'Library', 'Playlists', 'Friends', 'Radio', 'Profile'],
    },
  },
  {
    id: 'version-10',
    timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v2.2.0',
    description: 'Visual redesign with beautiful dark mode optimized for late-night listening sessions.',
    changeTitle: 'Dark mode launched',
    features: [
      'Dark Mode Support',
      'Redesigned Interface',
      'Crossfade Transitions',
      'Now Playing Notifications',
    ],
    browserState: {
      primaryColor: '#1E1E1E',
      accentColor: '#1DB954',
      layout: 'full',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: true,
      hasPlaylists: true,
      hasProfiles: true,
      hasSocial: true,
      hasLyrics: true,
      isDarkMode: true,
      heroText: 'Music in the Dark',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume', 'Repeat', 'Shuffle', 'Queue', 'EQ', 'Lyrics', 'Crossfade'],
      sidebarItems: ['Home', 'Search', 'Library', 'Playlists', 'Friends', 'Radio', 'Podcasts', 'Profile'],
    },
  },
  {
    id: 'version-11',
    timestamp: new Date(now.getTime() - 1 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v2.3.0',
    description: 'Personalized insights with comprehensive listening analytics and smart recommendations.',
    changeTitle: 'Analytics dashboard released',
    features: [
      'Listening Analytics Dashboard',
      'Year in Review',
      'Smart Mixes & AI Recommendations',
      'Top Artists & Tracks Stats',
    ],
    browserState: {
      primaryColor: '#1E1E1E',
      accentColor: '#1DB954',
      layout: 'full',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: true,
      hasPlaylists: true,
      hasProfiles: true,
      hasSocial: true,
      hasLyrics: true,
      isDarkMode: true,
      heroText: 'Your Year in Music',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume', 'Repeat', 'Shuffle', 'Queue', 'EQ', 'Lyrics', 'Crossfade', 'Smart Mix'],
      sidebarItems: ['Home', 'Search', 'Library', 'Playlists', 'Friends', 'Radio', 'Podcasts', 'Analytics', 'Profile'],
    },
  },
  {
    id: 'version-12',
    timestamp: new Date(now.getTime() - 0 * 60 * 60 * 1000),
    title: 'MusicFlow',
    version: 'v2.4.0',
    description: 'Ultimate music streaming experience with lossless HiFi audio and live event discovery.',
    changeTitle: 'HiFi audio & concert finder',
    features: [
      'HiFi Lossless Audio',
      'Spatial Audio Support',
      'Concert & Event Finder',
      'Live Performance Streams',
      'Enhanced Discovery Algorithm',
    ],
    browserState: {
      primaryColor: '#1E1E1E',
      accentColor: '#1DB954',
      layout: 'full',
      hasPlayer: true,
      hasSidebar: true,
      hasSearch: true,
      hasPlaylists: true,
      hasProfiles: true,
      hasSocial: true,
      hasLyrics: true,
      isDarkMode: true,
      heroText: 'The Ultimate Music Experience',
      playerFeatures: ['Play/Pause', 'Skip', 'Volume', 'Repeat', 'Shuffle', 'Queue', 'EQ', 'Lyrics', 'Crossfade', 'Smart Mix', 'HiFi'],
      sidebarItems: ['Home', 'Search', 'Library', 'Playlists', 'Friends', 'Radio', 'Podcasts', 'Analytics', 'Concert Finder', 'Profile'],
    },
  },
];
